steps:
  # Build and push the backend Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/sushflix-backend', './src/server']
    timeout: '1200s' # Adjust timeout as needed

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/sushflix-backend']

  # Deploy the backend FIRST to get its URL
  - name: 'gcr.io/cloud-builders/gcloud'
    id: Deploy Backend
    args:
      [
        'run',
        'deploy',
        'sushflix-backend',
        '--image',
        'gcr.io/$PROJECT_ID/sushflix-backend',
        '--platform',
        'managed',
        '--region',
        'us-central1',
        '--allow-unauthenticated',
        '--set-secrets',
        'CLIENT_ID=google-oauth-client-id:latest,CLIENT_SECRET=google-oauth-client-secret:latest,MONGO_URI=mongo-uri:latest,AWS_ACCESS_KEY_ID=aws-access-key-id:latest,AWS_SECRET_ACCESS_KEY=aws-secret-access-key:latest,JWT_SECRET=jwt-secret:latest',
        '--set-env-vars',
        'AWS_REGION=eu-north-1,AWS_BUCKET_NAME=sushflix'
      ]

  # Get the Google OAuth client ID from Secret Manager
  - name: 'gcr.io/cloud-builders/gcloud'
    id: Get Client ID
    args: ['secrets', 'versions', 'access', 'latest', '--secret=google-oauth-client-id']
    env:
      - 'CLIENT_ID=$$(gcloud secrets versions access latest --secret=google-oauth-client-id)'

  # Build and push the frontend Docker image, passing the backend URL and client ID as build-args
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t',
      'gcr.io/$PROJECT_ID/sushflix-frontend',
      '.',
      '--build-arg',
      'VITE_BACKEND_URL=https://sushflix-backend-796527544626.us-central1.run.app',
      '--build-arg',
      'VITE_CLIENT_ID=$$CLIENT_ID'
    ]
    timeout: '1200s'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/sushflix-frontend']

  # Deploy the frontend
  - name: 'gcr.io/cloud-builders/gcloud'
    id: Deploy Frontend
    args:
      [
        'run',
        'deploy',
        'sushflix-frontend',
        '--image',
        'gcr.io/$PROJECT_ID/sushflix-frontend',
        '--platform',
        'managed',
        '--region',
        'us-central1',
        '--allow-unauthenticated'
      ]

logsBucket: gs://sushflix-logs
