steps:
  # Build and push the backend Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/sushflix-backend', './src/server']
    timeout: '1200s' # Adjust timeout as needed

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/sushflix-backend']

  # Build and push the frontend Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/sushflix-frontend', '.']
    timeout: '1200s' # Adjust timeout as needed

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/sushflix-frontend']

# Deploy to Cloud Run after building
  - name: 'gcr.io/cloud-builders/gcloud'
    id: Deploy Backend
    args:
      [
        'run',
        'deploy',
        'sushflix-backend',
        '--image',
        'gcr.io/$PROJECT_ID/sushflix-backend',
        '--platform',
        'managed',
        '--region',
        'us-central1', # Replace with your desired region
        '--allow-unauthenticated', # Change to --no-allow-unauthenticated if needed
        '--set-env-vars',
        'MONGO_URI=mongodb+srv://qpwoeiruty9211:m5RRGZeMVe8AoILt@sushflix.0qovl.mongodb.net/?retryWrites=true&w=majority&appName=sushflix,AWS_ACCESS_KEY_ID=AKIAY6QVZPSXCWQD3UFH,AWS_SECRET_ACCESS_KEY=zPWmiP6J3fd@hefB5VZFZ7ZUT31HEI4MSeCH91CP,AWS_REGION=eu-north-1,AWS_BUCKET_NAME=sushflix' # Add other necessary env vars
      ]

  - name: 'gcr.io/cloud-builders/gcloud'
    id: Deploy Frontend
    args:
      [
        'run',
        'deploy',
        'sushflix-frontend',
        '--image',
        'gcr.io/$PROJECT_ID/sushflix-frontend',
        '--platform',
        'managed',
        '--region',
        'us-central1', # Replace with your desired region
        '--allow-unauthenticated', # Frontend is usually public
        '--update-env-vars', # This confirms the change was applied
        'VITE_BACKEND_URL=${steps['Deploy Backend'].uri}'
      ]

logsBucket: gs://sushflix-logs
