steps:
  # Build and push the backend Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t',
      'us-central1-docker.pkg.dev/$PROJECT_ID/sushflix-repo/sushflix-backend',
      './src/server'
    ]
    timeout: '1200s'

  # Push backend image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'us-central1-docker.pkg.dev/$PROJECT_ID/sushflix-repo/sushflix-backend'
    ]

  # Deploy backend with required secrets
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'run',
        'deploy',
        'sushflix-backend',
        '--image',
        'us-central1-docker.pkg.dev/$PROJECT_ID/sushflix-repo/sushflix-backend',
        '--platform',
        'managed',
        '--region',
        'us-central1',
        '--allow-unauthenticated',
        '--set-secrets',
        'MONGO_URI=mongo-uri:latest,JWT_SECRET=jwt-secret:latest',
        '--set-env-vars',
        'GCS_BUCKET_NAME=user-profile-pictures-sushflix'
      ]

  # Build and push the frontend Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t',
      'us-central1-docker.pkg.dev/$PROJECT_ID/sushflix-repo/sushflix',
      '.',
      '--build-arg',
      'VITE_BACKEND_URL=https://sushflix-backend-796527544626.us-central1.run.app',
      '--build-arg',
      'VITE_GCS_BUCKET_NAME=user-profile-pictures-sushflix'
    ]
    timeout: '1200s'

  # Push frontend image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'us-central1-docker.pkg.dev/$PROJECT_ID/sushflix-repo/sushflix'
    ]

  # Deploy the frontend
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'run',
        'deploy',
        'sushflix',
        '--image',
        'us-central1-docker.pkg.dev/$PROJECT_ID/sushflix-repo/sushflix',
        '--platform',
        'managed',
        '--region',
        'us-central1',
        '--allow-unauthenticated'
      ]

logsBucket: gs://sushflix-logs
